### ISSUE TITLE
Website’s images and assets

### ISSUE THREAD

**Issue by schegde** [cocotb/cocotb-web#24]
Hi! I come from a hardware design background, and started using cocotb recently! I came across this repo as the source code for your well designed website. I was curious how you designed some of these logos/images in the `assets`. (Just want to know which tools you used to create those). I like using cocotb, so thanks for keeping it all open source!! :)

**Comment by cmarqu** [comment]
We had a designer do it for us, and IIRC these are stock images, a bit customized in parts.

**Comment by imphil** [comment]
Yeah, unfortunately don't know which tools the designers used. I guess that's all we can help you with here, I know it's not much :(
