### ISSUE TITLE
Random thoughts on the website

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb-web#3]
I like it!

Some small things...
* [x] The "Fast" in the big blue heading... people might take that as "great simulation performance", while we mean... "swift" maybe? *-> imphil: went for productive*
* [x] The smiley is 3D, might want to use a flat design, maybe in "our" colors? *-> removed the smiley, it looks odd on Windows I found out.*
* [x] Doesn't have a favicon
* [x] `assets/img/process-icon-1.svg` (-2 and -3 as well) uses a serif font for the number (Chrome on a Mac, non-serif on Android) *-> sorted by converting the SVG text to a path.*
* [x] `<title/>` is a bit too long IMO
* [x] s/You're ready to run your test!/You are ready to run your test!/
* [x] Should we maybe normalize to always write "cocotb" in lowercase, even at the start of a sentence? The website (and the docs, I admit) is not consistent there.
* [x] "cocotb is free. And priceless" - add period
* [x] swap the icons for "cocotb is not an island" (so that it has the chip icon, looks a bit island-ey) and "Easy to learn" (so that it has the brain icon)
* [x]  If easily possible, remove the dropshadow from https://www-preview.cocotb.org/assets/img/python-in-circle.svg for consistency with the other icons.
* [x] https://www-preview.cocotb.org/assets/img/benefits-1.svg is also better suited for "CI-capable test runner included" IMO
* [x] Maybe make the text under "cocotb is free. And priceless." flush left (i.e. not centered) to match all other paragraphs?
* [ ] #4

**Comment by cmarqu** [comment]
If easily possible, remove the dropshadow from https://www-preview.cocotb.org/assets/img/python-in-circle.svg for consistency with the other icons.

**Comment by cmarqu** [comment]
- [ ] https://www-preview.cocotb.org/assets/img/benefits-1.svg is also better suited for "CI-capable test runner included" IMO

**Comment by imphil** [comment]
Thanks @cmarqu for having a first look! I addressed the first set of issues (and a couple other things) and updated https://www-preview.cocotb.org/. There's more to be done, but that's for tomorrow. Keep the suggestions coming!

**Comment by themperek** [comment]
- Download button is not functional
- The tile is maybe too big, especially on mobile.

**Comment by cmarqu** [comment]
- [ ] Maybe make the text under "cocotb is free. And priceless." flush left (i.e. not centered) to match all other paragraphs?

**Comment by imphil** [comment]
@themperek @cmarqu I addressed all comments here and updated the preview. PTAL.

**Comment by themperek** [comment]
For me looks OK. 

PS. Maybe could ask for some testimonials when going live.

**Comment by imphil** [comment]
Great, let's call this issue resolved then for now.
