### ISSUE TITLE
Add a blog

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb-web#6]
Currently, we post on the FOSSi Foundation blog. Maybe we should get our own?

**Comment by imphil** [comment]
Possible content:
- Release notes
- Use cases
- Reposts of content created by users on others places (e.g. how to use cocotb + matlab)

**Comment by cmarqu** [comment]
Some resources for reposting are listed at https://github.com/cocotb/cocotb/wiki/Further-Resources
