### ISSUE TITLE
Icon duplicated

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb-web#7]
The icon used in "Works with what you have" is a duplicate of the "CI-runner..." tile now.

**Comment by imphil** [comment]
Yeah, as you requested in https://github.com/cocotb/cocotb-web/issues/3 (" www-preview.cocotb.org/assets/img/benefits-1.svg is also better suited for "CI-capable test runner included" IMO) :-) Did I misunderstand you there, or should we try to find another icon? (If so, any ideas?)

**Comment by cmarqu** [comment]
Oh, I meant "swap the icons".
