### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by cmarqu** [cocotb/cocotb-web#9]
- [x] cocotbs extensive documentation -> cocotb's extensive documentation
- [x] Who's -> Who is
- [x] you're ready to go -> you are ready to go
- [x] help us with e.g. with licenses -> help us e.g. with licenses

**Comment by imphil** [comment]
You don't really like short forms, it seems :-) I honestly don't see much of a problem there. What do others think? @ktbarrett

**Comment by cmarqu** [comment]
I was taught that one doesn't use contractions in "formal" texts, but it's quite possible that times have changed since then.

**Comment by ktbarrett** [comment]
I don't mind either way.

> I was taught that one doesn't use contractions in "formal" texts

I was taught the same, but I was also taught to not use fragments ***ever***, or emotional or opinionated language. But we have fragments, "smiles", "goodness", "productivity", and "enjoyable", so I'm not sure we are in "formal" land anymore.

**Comment by imphil** [comment]
The copy on the website is marketing text, where we ultimately can do whatever we want: we can make it sound formal or informal, "serious enterprise software" or "crazy open source community". I went for a slightly informal style to show that we're not an old-school EDA tool you buy expensive licenses for, but a professional, yet "fresh" alternative. Of course, neither this tone of voice nor the implementation of it are set in stone, so I'm happy for suggestions!

**Comment by imphil** [comment]
Just for reference: here's a letter I got today from the National Trust, a traditional British heritage protection charity. Contractions everywhere; I think we have simply moved on in 2022.

![grafik](https://user-images.githubusercontent.com/1467123/150518230-2f04071e-3fd3-4b11-90e5-e784f2dfbafc.png)
